import { FormEvent, useEffect, useState } from 'react';
import { Activity, AlertTriangle, BedDouble, CalendarDays, ChevronRight, CircleDollarSign, LayoutDashboard, LogOut, Package, Settings, ShieldCheck, Users } from 'lucide-react';
import { api, setToken } from './api';

type User = { name: string; role: string; email: string };
type Dashboard = { kpis: { patients:number; today_appointments:number; occupancy:number; available_beds:number; revenue:number; pending_bills:number } };
const links = [['Overview',LayoutDashboard],['Patients',Users],['Appointments',CalendarDays],['Bed management',BedDouble],['Inventory',Package],['Billing',CircleDollarSign],['Analytics',Activity]] as const;

export default function App() {
 const [user,setUser]=useState<User>({name:'Avery Morgan',role:'ADMIN',email:'admin@northstar.health'}); const [auth,setAuth]=useState(Boolean(localStorage.getItem('northstar_token'))); const [page,setPage]=useState('Overview'); const [data,setData]=useState<Dashboard>(); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!auth){setLoading(false);return;} Promise.all([api.get('/dashboard'),api.get('/auth/me')]).then(([d,p])=>{setData(d.data);setUser({name:p.data.full_name,role:p.data.role,email:p.data.email});}).catch(()=>{localStorage.removeItem('northstar_token');setAuth(false);}).finally(()=>setLoading(false));},[auth]);
 if(!auth)return <Login onLogin={login=>{setToken(login.access_token);setUser({name:login.full_name,role:login.role,email:login.email});setAuth(true);}}/>;
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><ShieldCheck size={20}/></div><div><strong>northstar</strong><span>HEALTH SYSTEM</span></div></div><div className="workspace-label">OPERATIONS WORKSPACE</div><nav>{links.map(([label,Icon])=><button key={label} className={page===label?'nav-item active':'nav-item'} onClick={()=>setPage(label)}><Icon size={18}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className={page==='Settings'?'nav-item active':'nav-item'} onClick={()=>setPage('Settings')}><Settings size={18}/><span>Settings</span></button><div className="security-note"><ShieldCheck size={17}/><div><b>Protected workspace</b><span>HIPAA-ready controls enabled</span></div></div></div></aside><main className="main"><header className="topbar"><div className="crumb"><span>Operations</span><ChevronRight size={15}/><b>{page}</b></div><div className="user"><div className="avatar">{user.name.split(' ').map(x=>x[0]).join('')}</div><div><b>{user.name}</b><span>{user.role}</span></div><button className="logout" onClick={()=>{localStorage.removeItem('northstar_token');setAuth(false);}}><LogOut size={17}/></button></div></header><div className="content">{page==='Settings'?<SettingsPanel user={user} onSaved={setUser}/>:<Overview data={data} loading={loading}/>}</div></main></div>;
}
function Login({onLogin}:{onLogin:(data:{access_token:string;full_name:string;role:string;email:string})=>void}){const [email,setEmail]=useState('admin@northstar.health');const [password,setPassword]=useState('Admin123!');const [error,setError]=useState('');const submit=async(e:FormEvent)=>{e.preventDefault();try{onLogin((await api.post('/auth/login',{email,password})).data);}catch{setError('Sign in failed. Check your email and password.');}};return <div className="login-page"><div className="login-aside"><div className="brand login-brand"><div className="brand-mark"><ShieldCheck size={20}/></div><div><strong>northstar</strong><span>HEALTH SYSTEM</span></div></div><div className="login-quote"><span>OPERATIONS INTELLIGENCE</span><h1>Make every<br/><em>moment</em> count.</h1><p>A calmer command center for the people keeping care moving.</p></div></div><main className="login-card"><div className="login-card-inner"><div className="eyebrow">ADMIN CONSOLE</div><h2>Welcome back</h2><p className="login-subtitle">Sign in to your Northstar workspace.</p>{error&&<div className="login-error"><AlertTriangle size={15}/>{error}</div>}<form onSubmit={submit}><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="login-button">Sign in to workspace <ChevronRight size={17}/></button></form><div className="demo-note"><span className="status-pip amber"/> Demo admin access is prefilled</div></div></main></div>;}
function Overview({data,loading}:{data?:Dashboard;loading:boolean}){if(loading)return <div className="loading-state"><div className="spinner"/><b>Loading operations workspace</b></div>;if(!data)return <div className="empty-state"><Activity size={28}/><b>No operations data</b></div>;const k=data.kpis;return <><section className="page-heading"><div><div className="eyebrow">SATURDAY, AUGUST 22, 2026 <span className="live-dot"/> LIVE</div><h1>Good morning, Avery</h1><p>Here is the operational pulse across Northstar Health.</p></div></section><section className="pulse-banner"><div className="pulse-orbit"><Activity size={20}/></div><div className="pulse-copy"><span className="eyebrow">NORTHSTAR PULSE</span><h2>Hospital operations are steady.</h2><p>Capacity is holding at <b>{k.occupancy}%</b> with <b>{k.available_beds} beds</b> ready.</p></div><div className="pulse-stat"><span>Today's revenue</span><strong>${k.revenue.toLocaleString()}</strong><small>{k.pending_bills} pending bills</small></div></section><section className="kpi-grid"><Kpi label="Total patients" value={k.patients} icon={Users} tone="teal"/><Kpi label="Today's appointments" value={k.today_appointments} icon={CalendarDays} tone="coral"/><Kpi label="Bed occupancy" value={`${k.occupancy}%`} icon={BedDouble} tone="blue"/><Kpi label="Available beds" value={k.available_beds} icon={Activity} tone="gold"/></section></>;}
function Kpi({label,value,icon:Icon,tone}:{label:string;value:string|number;icon:any;tone:string}){return <div className="kpi"><div className={`kpi-icon ${tone}`}><Icon size={19}/></div><span className="kpi-label">{label}</span><strong>{value}</strong><small>Live from hospital operations</small></div>;}
function SettingsPanel({user,onSaved}:{user:User;onSaved:(user:User)=>void}){const [name,setName]=useState(user.name);const [email,setEmail]=useState(user.email);const [message,setMessage]=useState('');const save=async(e:FormEvent)=>{e.preventDefault();try{const r=await api.patch('/auth/me',{full_name:name,email});onSaved({name:r.data.full_name,email:r.data.email,role:r.data.role});setMessage('Profile information saved.');}catch{setMessage('Unable to save changes.');}};return <section className="settings-page"><div className="page-heading"><div><div className="eyebrow">ACCOUNT SETTINGS</div><h1>Admin profile</h1><p>Update the information shown across your workspace.</p></div></div><div className="settings-layout"><div className="settings-intro"><div className="settings-avatar">{user.name.split(' ').map(x=>x[0]).join('')}</div><h2>{user.name}</h2><span className="role-badge">{user.role}</span><p>Administrator access</p></div><form className="settings-form" onSubmit={save}><div className="form-heading"><div><h2>Personal information</h2><p>These details identify you to your operations team.</p></div><ShieldCheck size={20}/></div><label>Full name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Work email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Role<input value={user.role} disabled/></label><div className="settings-actions"><span className="save-message">{message}</span><button className="primary-button">Save changes</button></div></form></div></section>;}
